gui-libs/gtk: require media-libs/vulkan-loader[X?]
Installation of `gui-libs/gtk[X]` with `media-libs/vulkan-loader[-X]`
later causes compilation errors in `media-libs/glycin`:
```
env PKG_CONFIG_PATH=/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/meson-uninstalled:/var/tmp/portage/media-libs/glycin-9999-r20101/temp/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:/usr/share/pkgconfig PKG_CONFIG_LIBDIR=/usr/lib64/pkgconfig PKG_CONFIG=/usr/bin/x86_64-pc-linux-gnu-pkg-config CC=clang 'CFLAGS=-O2 -pipe -march=native -frecord-gcc-switches -Werror=odr -Werror=strict-aliasing -Wno-incompatible-pointer-types -Wl,--defsym=__gentoo_check_ldflags__=0' /usr/bin/g-ir-scanner --quiet --no-libtool --namespace=GlyGtk4 --nsversion=2 --warn-all --output libglycin/GlyGtk4-2.gir --c-include=glycin-gtk4.h -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999/libglycin -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999/libglycin/include/ -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin/include/ --filelist=/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin/libglycin-gtk4-2.so.0.p/GlyGtk4_2_gir_filelist -L/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin --extra-library=glycin-2 --include=GLib-2.0 --include=GObject-2.0 --include=Gio-2.0 --include=Gly-2 --include=Gdk-4.0 --symbol-prefix=gly_gtk --pkg-export=glycin-gtk4-2 --cflags-begin -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999/libglycin/include/ -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin/include/ -I/usr/include/freetype2 -DWITH_GZFILEOP -I/usr/lib64/libffi/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/webp -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/graphene-1.0 -I/usr/lib64/graphene-1.0/include -I/usr/include/gobject-introspection-1.0 --cflags-end -I/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin --add-include-path=/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin --add-include-path=/usr/share/gir-1.0 --add-include-path=/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin -L/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin --library glycin-gtk4-2 -L/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/libglycin --extra-library=fontconfig --extra-library=gio-2.0 --extra-library=gobject-2.0 --extra-library=glib-2.0 --extra-library=seccomp --extra-library=lcms2 --extra-library=lcms2_fast_float --extra-library=lcms2_threaded --extra-library=gtk-4 --extra-library=pangocairo-1.0 --extra-library=pango-1.0 --extra-library=harfbuzz --extra-library=gdk_pixbuf-2.0 --extra-library=cairo-gobject --extra-library=cairo --extra-library=vulkan --extra-library=graphene-1.0 --extra-library=girepository-1.0 --sources-top-dirs /var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999/ --sources-top-dirs /var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/
clang: warning: -Wl,--defsym=__gentoo_check_ldflags__=0: 'linker' input unused [-Wunused-command-line-argument]
/var/tmp/portage/media-libs/glycin-9999-r20101/work/glycin-9999-build/tmp-introspect3lq0l5w7/GlyGtk4-2: symbol lookup error: /usr/lib64/libgtk-4.so.1: undefined symbol: vkCreateXlibSurfaceKHR
```
(where `vkCreateXlibSurfaceKHR` is a part of `media-libs/vulkan-loader[X]`)

Signed-off-by: Sv. Lockal <lockalsash@gmail.com>